### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by dwijnand** [dwijnand/sbt-travisci#1]

**Comment by dwijnand** [comment]
@djspiewak I'm keen to get this out.

So I'm going to cut a 1.0.0-M1 release, so people can start using it. Perhaps you can start using it yourself, and (I expect very probably) refine my build matrix support.

In, say, 10 days I'll cut a proper 1.0.0 and announce it.

**Comment by djspiewak** [comment]
:+1: I'm very much in favor of cutting a proper release.  We would immediately swap over our hacky internal logic to use a standardized plugin.

**Comment by dwijnand** [comment]
1.0.0-M2 is out and I've PR'd wartremover to switch to it.

Do you want to give it a spin on your various projects so we can refine it's behaviour and commit to 1.0.0?

**Comment by djspiewak** [comment]
@dwijnand I'll see about giving it a shot on a few of our matrixed builds.  It'll probably take a week or two before I have things pushed through, but if things go wrong I'll have results sooner.  Will report back!

**Comment by djspiewak** [comment]
Requesting: 1.0.0-M3.

**Comment by dwijnand** [comment]
I'm afk. Tag it and push it and it'll publish. Or I'll do it when I'm home.

Also there's a 1.0.0M2+etc version released as of merging your PR into master.

**Comment by djspiewak** [comment]
Tagged and pushed M3.  M2 looked like it was pre-PR, and I couldn't find another release, but maybe I just looked in the wrong place. :-) Either way… Good now!

**Comment by dwijnand** [comment]
How we looking? Shall we bite the bullet and commit to 1.0.0?

**Comment by djspiewak** [comment]
Oh I forgot to try enabling the matrix-based build.

**Comment by djspiewak** [comment]
@dwijnand After dredging through our org's set of repositories, the only ones I can find which are using matrix builds are open source!  For example, [Verizon/knobs](https://github.com/Verizon/knobs).

We've had this as part of our core build plugin since M4 though, and while a lot of internal projects do tend to lag a version or two behind on the plugin, I think it's absolutely tested enough that I'm comfortable stamping a "1.0" on it.  If we find there are some corner cases (e.g. weird matrix builds) that aren't working, we could push up the minor version.  If, in future, we think it would be cool to add more general Travis functionality to the plugin (as the name sort of implies), that could go in a major release.

But as it stands, the plugin is absolutely useful and more than stable enough to merit a full release.

**Comment by djspiewak** [comment]
@dwijnand Want me to tag and push a 1.0.0?

**Comment by dwijnand** [comment]
Oh yeah. Lemme do some release notes for your improvements. I'll do it in the morning.

**Comment by dwijnand** [comment]
Done. https://github.com/dwijnand/sbt-travisci/releases/tag/v1.0.0
